version: '3.8'

services:
  api:
    container_name: investmoscow_parser_api
    build: .
    depends_on:
      - db
      - redis
    command: bash -c 'uvicorn app.app:app --reload --host ${API_HOST} --port ${API_PORT}'
    volumes:
      - ./app:/src/app/
      - ./jsons:/src/jsons/
      - ./reports:/src/reports/
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    environment:
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    env_file:
      - .env

  db:
    container_name: investmoscow_parser_db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    restart: unless-stopped
    env_file:
      - .env

  redis:
    container_name: investmoscow_parser_redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env

